on:
  push:
    branches:
      - master
  schedule:
  # should run at midnight 20th day of each month
    - cron:  '0 0 20 * *'

name: update-count-tables

jobs:
  update-count-tables:
    runs-on: ubuntu-20.04
    container:
      image: grimbough/conda-stats
    steps:
    
    - name: install git lfs 
      run: | 
        sudo apt-get -y update
        sudo apt-get -y install git-lfs
        git lfs install
    
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Checkout LFS objects
      run: git lfs checkout
    
    - name: Cache processed monthly tables
      uses: actions/cache@v2
      env:
        cache-name: monthly-tables
      with:
        path: rdata/monthly
        key: ${{ runner.os }}-${{ env.cache-name }}
        
    - name: Process new counts
      run: Rscript R/update_tables.R
      
    - name: Compress TSV files
      run: |
        gzip -f -n tsv/*.tsv
      
    - name: commit updated tables
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add rdata/all_counts.rds rdata/bioc_counts.rds 
        git add tsv/all_counts.tsv.gz tsv/bioc_counts.tsv.gz
        git commit -m "`date +%B` update" || echo "No changes to commit"
        git push origin master || echo "No changes to commit"
      
